# Generated by Django 2.1.5 on 2019-01-22 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190121_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='artist_first_name',
            new_name='artist_name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='artist_last_name',
        ),
    ]
