# Generated by Django 2.1.5 on 2019-01-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20190122_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='pub_year',
            field=models.IntegerField(default=0),
        ),
    ]
